/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userPanel_sys;

import com.sun.xml.internal.ws.api.streaming.XMLStreamWriterFactory;
import java.awt.event.ComponentEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Matcher;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;

/**
 *
 * @author Prottoy
 */
public class userPanel extends javax.swing.JFrame {

    /**
     * Creates new form userPanel
     */
    DefaultTableModel dm,dm1,dm2;
    int cid ;
    public userPanel() {
        initComponents();
//        openpdf("C:\\Users\\Prottoy\\Pictures\\Screenshots");
//        setExtendedState(MAXIMIZED_BOTH);
        CreatColums();
        CreatClassRows();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanleSlider = new javax.swing.JPanel();
        MenuClosed = new javax.swing.JLabel();
        jLabelSettings = new javax.swing.JLabel();
        jLabelClasses = new javax.swing.JLabel();
        jLabelHome = new javax.swing.JLabel();
        MenuOpened = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jButton_Remove_Class_ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jText_Semester_ = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jText_Course_Name_ = new javax.swing.JTextField();
        jButton_Open_class_lectures_ = new javax.swing.JButton();
        jButton_Add_Classes_ = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClasses = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_lectures_ = new javax.swing.JTable();
        jButton_add_lect_ = new javax.swing.JButton();
        jButton_open_lec_ = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_course_name_ = new javax.swing.JTable();
        jButton_Remove_lectures = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jPanel1.setForeground(new java.awt.Color(60, 63, 65));
        jPanel1.setMinimumSize(new java.awt.Dimension(1243, 718));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanleSlider.setBackground(new java.awt.Color(102, 0, 102));
        jPanleSlider.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuClosed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuClosed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userPanel_sys/menu (2).png"))); // NOI18N
        MenuClosed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuClosed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuClosedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuClosedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuClosedMouseExited(evt);
            }
        });
        jPanleSlider.add(MenuClosed, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 50, 50));

        jLabelSettings.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelSettings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userPanel_sys/settings.png"))); // NOI18N
        jLabelSettings.setText("Lectures");
        jLabelSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSettingsMouseClicked(evt);
            }
        });
        jPanleSlider.add(jLabelSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 230, 60));

        jLabelClasses.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelClasses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClasses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userPanel_sys/class.png"))); // NOI18N
        jLabelClasses.setText("Classes");
        jLabelClasses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClasses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClassesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelClassesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelClassesMouseExited(evt);
            }
        });
        jPanleSlider.add(jLabelClasses, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 230, 60));

        jLabelHome.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userPanel_sys/house.png"))); // NOI18N
        jLabelHome.setText("Home");
        jLabelHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseEntered(evt);
            }
        });
        jPanleSlider.add(jLabelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 230, 60));

        jPanel1.add(jPanleSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 720));

        MenuOpened.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuOpened.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userPanel_sys/menu (4).png"))); // NOI18N
        MenuOpened.setOpaque(true);
        MenuOpened.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuOpenedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuOpenedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuOpenedMouseExited(evt);
            }
        });
        jPanel1.add(MenuOpened, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 50));

        jPanel4.setToolTipText("");
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Remove_Class_.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton_Remove_Class_.setText("Remove the selected classes");
        jButton_Remove_Class_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Remove_Class_ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Remove_Class_, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, 240, 20));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Semester");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, -1, -1));
        jPanel2.add(jText_Semester_, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 340, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Course Name ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, -1, -1));

        jText_Course_Name_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_Course_Name_ActionPerformed(evt);
            }
        });
        jPanel2.add(jText_Course_Name_, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 340, 40));

        jButton_Open_class_lectures_.setText("Show Class Lectures");
        jButton_Open_class_lectures_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Open_class_lectures_ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Open_class_lectures_, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 180, 50));

        jButton_Add_Classes_.setText("Add Classes ");
        jButton_Add_Classes_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_Classes_ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Add_Classes_, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 630, 150, 50));

        jTableClasses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableClasses.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jTableClasses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClassesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClasses);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1010, 250));

        jLayeredPane1.add(jPanel2, "card3");

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_lectures_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_lectures_.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane2.setViewportView(jTable_lectures_);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1010, 290));

        jButton_add_lect_.setText("Add Lectures");
        jButton_add_lect_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_lect_ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_add_lect_, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 150, 50));

        jButton_open_lec_.setText("Open Selected Lecture");
        jButton_open_lec_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_open_lec_ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_open_lec_, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 200, 50));

        jTable_course_name_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTable_course_name_);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 40));

        jButton_Remove_lectures.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton_Remove_lectures.setText("Remove the selected Lectures");
        jButton_Remove_lectures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Remove_lecturesActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_Remove_lectures, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, 240, 20));

        jLayeredPane1.add(jPanel3, "card2");
        jLayeredPane1.add(jScrollPane3, "card4");

        jPanel4.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 720));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 1010, 720));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1265, 774));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    int x = 230;
    private void MenuClosedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuClosedMouseClicked
        // TODO add your handling code here:
        
        if (x==230) {
            jPanleSlider.setSize(230,720);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try {
                        for (int i = 230;i >0; i--) {
                            Thread.sleep(1);
                            jPanleSlider.setSize(i,720);
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };th.start();
            x=0;
            
        }
    }//GEN-LAST:event_MenuClosedMouseClicked

    private void MenuOpenedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuOpenedMouseClicked
        // TODO add your handling code here:
        if (x==0) {
            jPanleSlider.show();
            jPanleSlider.setSize(x,720);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try {
                        for (int i = 0;i <=x ; i++) {
                            Thread.sleep(1);
                            jPanleSlider.setSize(i,720);
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };th.start();
            x=230;
        }
    }//GEN-LAST:event_MenuOpenedMouseClicked

    private void MenuClosedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuClosedMouseEntered
        // TODO add your handling code here:
        lablecolor(MenuClosed);
    }//GEN-LAST:event_MenuClosedMouseEntered

    private void MenuClosedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuClosedMouseExited
        // TODO add your handling code here:
        resetlablecolor(MenuClosed);
    }//GEN-LAST:event_MenuClosedMouseExited

    private void MenuOpenedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuOpenedMouseEntered
        // TODO add your handling code here:
        resetlablecolor(MenuOpened);
    }//GEN-LAST:event_MenuOpenedMouseEntered

    private void MenuOpenedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuOpenedMouseExited
        // TODO add your handling code here:\
        lablecolor(MenuOpened);
    }//GEN-LAST:event_MenuOpenedMouseExited

    private void jButton_Remove_Class_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Remove_Class_ActionPerformed
        // TODO add your handling code here
        
        JOptionPane.showMessageDialog(null, "Are Sure you want to remove this course \n All the lectures with the course will be permanently deleated"); //****!!!! Make improvements
//        dm.removeRow(jTableClasses.getSelectedRow());
        
        int[] selectedRows = jTableClasses.getSelectedRows();
        if (selectedRows.length > 0) {
            for (int i = selectedRows.length - 1; i >= 0; i--) {
                try {
                        Class.forName("com.mysql.jdbc.Driver");
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/note_organiser","root","");
                        Statement smt = con.createStatement();
                        
                        String rmvClass = jTableClasses.getValueAt(selectedRows[i],0).toString();
                                
                        String sql1 = "DELETE FROM `course` WHERE `course name` = '"+rmvClass+"';";
                        System.out.print(sql1);
                        smt.executeUpdate(sql1);
                        
                        } catch (Exception e1) {
                                // TODO Auto-generated catch block
                                e1.printStackTrace();
                        }                
                dm.removeRow(selectedRows[i]);
//                dm.setRowCount(0);
//                dm.setColumnCount(0);
               
            }
        }
        
        
    }//GEN-LAST:event_jButton_Remove_Class_ActionPerformed

    private void jButton_Open_class_lectures_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Open_class_lectures_ActionPerformed
        // TODO add your handling code here:
        
        
        if (jTableClasses.getSelectedRow()>=0) {
            String seclclass = jTableClasses.getValueAt(jTableClasses.getSelectedRow(),0).toString();
    //      System.out.println(seclclass);
            dm2.setColumnCount(0);
            dm2.addColumn(seclclass);
        
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/note_organiser","root","");
                Statement smt = con.createStatement();


                String sql2 = "SELECT `course_id` FROM `course` WHERE `course name` = '"+seclclass+"';";  
                ResultSet ck = smt.executeQuery(sql2);
                if (ck.next()) {
                    cid = Integer.parseInt(ck.getString("course_id"));
                    System.out.println(cid);
                    }
                
                String sql3 = "SELECT * FROM `lectures` WHERE `course_id` = '"+cid+"';";
                System.out.print(sql3);
                ResultSet dk = smt.executeQuery(sql3);
                dm1.setRowCount(0);
                while (dk.next()) {
                    Creat_Lec_Rows(dk.getString("name"), dk.getString("path"));
                }
                

                //removing panel
            jLayeredPane1.removeAll();
            jLayeredPane1.repaint();
            jLayeredPane1.revalidate();
            //adding panel
            jLayeredPane1.add(jPanel3);
            jLayeredPane1.repaint();
            jLayeredPane1.revalidate();

            } catch (Exception e1) {
            // TODO Auto-generated catch block
                    e1.printStackTrace();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select 1 row");
        }
        
        
                
        
        
    }//GEN-LAST:event_jButton_Open_class_lectures_ActionPerformed

    private void jText_Course_Name_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_Course_Name_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_Course_Name_ActionPerformed

    private void jButton_Add_Classes_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_Classes_ActionPerformed
        // TODO add your handling code here:
        
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/note_organiser","root","");
        Statement smt = con.createStatement();
        System.out.print("hfhgf");
        String sql1 = "INSERT INTO `course`( `course name`, `semester`) VALUES  ('"+jText_Course_Name_.getText()+"', '"+jText_Semester_.getText()+"');";
        System.out.print(sql1);
//        smt.executeUpdate(sql1);
        smt.executeUpdate(sql1);
        

        String sql2 = "SELECT * FROM `course` WHERE `course name` = '"+jText_Course_Name_.getText()+ "';";
        System.out.print(sql2);
        ResultSet ck = smt.executeQuery(sql2);
        if (ck.next()) {
            CreatRows(ck.getString("course name"), ck.getString("semester"));
        }

        } catch (Exception e1) {
                // TODO Auto-generated catch block
                e1.printStackTrace();
        }
        
//        CreatRows(jTextCourse_Name.getText(), jTextSemester.getText());
        
        jText_Course_Name_.setText("");
        jText_Semester_.setText("");
    }//GEN-LAST:event_jButton_Add_Classes_ActionPerformed

    private void jTableClassesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClassesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableClassesMouseClicked

    private void jButton_add_lect_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_lect_ActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser filechooser = new JFileChooser();
            int value = filechooser.showOpenDialog(null);
            if (value==JFileChooser.APPROVE_OPTION) {
                String path = filechooser.getSelectedFile().toString();
                String name = filechooser.getSelectedFile().getName();
                
                //This pice of code is used to replace the single \ in the 'path' string with 
                path = path.replaceAll(Matcher.quoteReplacement("\\"), Matcher.quoteReplacement("\\\\"));
                System.out.println(path);
//                Creat_Lec_Rows(name,path);
                
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/note_organiser","root","");
                Statement smt = con.createStatement();
                
                String sql1 = "INSERT INTO `lectures`(`course_id`, `name`, `path`) VALUES ('"+cid+"','"+name+"','"+path+"');";
                System.out.println(sql1);
                smt.executeUpdate(sql1);
                
                String sql2 = "SELECT * FROM `lectures` WHERE `course_id` = '"+cid+"';";
                System.out.print(sql2);
                ResultSet ck = smt.executeQuery(sql2);
                if (ck.next()) {
                    Creat_Lec_Rows(ck.getString("name"), ck.getString("path"));
                }

                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_jButton_add_lect_ActionPerformed

    private void jLabelHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseEntered
        // TODO add your handling code here:
//        lablecolor(jLabelHome);
    }//GEN-LAST:event_jLabelHomeMouseEntered

    private void jLabelClassesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClassesMouseEntered
        // TODO add your handling code here:
        lablecolor(jLabelClasses);
    }//GEN-LAST:event_jLabelClassesMouseEntered

    private void jLabelClassesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClassesMouseExited
        // TODO add your handling code here:
        resetlablecolor(jLabelClasses);
    }//GEN-LAST:event_jLabelClassesMouseExited

    private void jLabelClassesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClassesMouseClicked
        // TODO add your handling code here:
        //removing panel
        jLayeredPane1.removeAll();
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
        //adding panel
        jLayeredPane1.add(jPanel2);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/note_organiser","root","");
            Statement smt = con.createStatement();
					
	dm.setRowCount(0);
	String sql2 = "SELECT `course_id`, `course name`, `semester` FROM `course`;";
	ResultSet ck = smt.executeQuery(sql2);
        while (ck.next()) {
                CreatRows(ck.getString("course name"), ck.getString("semester"));
        }

} catch (Exception e1) {
        // TODO Auto-generated catch block
        e1.printStackTrace();
}
        
    }//GEN-LAST:event_jLabelClassesMouseClicked

    private void jButton_open_lec_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_open_lec_ActionPerformed
        // TODO add your handling code here:
        String lecPath = jTable_lectures_.getValueAt(jTable_lectures_.getSelectedRow(), 1).toString();
        openpdf(lecPath);
        
        //removing panels
        jLayeredPane1.removeAll();
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
        //adding panel
        jLayeredPane1.add(jScrollPane3);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }//GEN-LAST:event_jButton_open_lec_ActionPerformed

    private void jButton_Remove_lecturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Remove_lecturesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Are Sure you want to parmanently remove the Lecture/s. \n Once delected it cannot be undone "); //****!!!! Make improvements
//        dm.removeRow(jTableClasses.getSelectedRow());
        
        int[] selectedRows = jTable_lectures_.getSelectedRows();
        if (selectedRows.length > 0) {
            for (int i = selectedRows.length - 1; i >= 0; i--) {
                try {
                        Class.forName("com.mysql.jdbc.Driver");
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/note_organiser","root","");
                        Statement smt = con.createStatement();
                        
                        String rmvClass = jTable_lectures_.getValueAt(selectedRows[i],0).toString();
                                
                        String sql1 = "DELETE FROM `lectures` WHERE `name` = '"+rmvClass+"' AND `course_id` = '"+cid+"';";
                        System.out.print(sql1);
                        smt.executeUpdate(sql1);
                        
                        } catch (Exception e1) {
                                // TODO Auto-generated catch block
                                e1.printStackTrace();
                        }                
                dm1.removeRow(selectedRows[i]);
//                dm.setRowCount(0);
//                dm.setColumnCount(0);
            }
        }
    }//GEN-LAST:event_jButton_Remove_lecturesActionPerformed

    private void jLabelSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSettingsMouseClicked
        // TODO add your handling code here:
        jLayeredPane1.removeAll();
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
        //adding panel
        jLayeredPane1.add(jPanel3);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }//GEN-LAST:event_jLabelSettingsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenuClosed;
    private javax.swing.JLabel MenuOpened;
    private javax.swing.JButton jButton_Add_Classes_;
    private javax.swing.JButton jButton_Open_class_lectures_;
    private javax.swing.JButton jButton_Remove_Class_;
    private javax.swing.JButton jButton_Remove_lectures;
    private javax.swing.JButton jButton_add_lect_;
    private javax.swing.JButton jButton_open_lec_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelClasses;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelSettings;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanleSlider;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableClasses;
    private javax.swing.JTable jTable_course_name_;
    private javax.swing.JTable jTable_lectures_;
    private javax.swing.JTextField jText_Course_Name_;
    private javax.swing.JTextField jText_Semester_;
    // End of variables declaration//GEN-END:variables
    
    private void lablecolor(JLabel label){
        label.setBackground(new java.awt.Color(232,239,244));
    }
    private void resetlablecolor(JLabel label){
        label.setBackground(new java.awt.Color(102,0,102));
    }
    
    private void CreatColums(){
        dm = (DefaultTableModel) jTableClasses.getModel();
        dm1 = (DefaultTableModel) jTable_lectures_.getModel();
        dm2 = (DefaultTableModel) jTable_course_name_.getModel();
        dm.addColumn("Courese");
        dm.addColumn("Semester");
        dm1.addColumn("Lectures");
        dm1.addColumn("Path");
//        dm.addColumn("Path");
    }
    
    private void CreatRows(String courseName, String semester){
//        dm =  (DefaultTableModel) jTableClasses.getModel();
        String [] rdata = {courseName,semester};
        dm.addRow(rdata);
//        dm.addRow("Courese");
//        dm.addColumn("Semester");
    }
    
    private void Creat_Lec_Rows(String courseName, String semester){
//        dm =  (DefaultTableModel) jTableClasses.getModel();
        String [] rdata = {courseName,semester};
        dm1.addRow(rdata);
//        dm.addRow("Courese");
//        dm.addColumn("Semester");
    }
    
    private void CreatClassRows(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/note_organiser","root","");
            Statement smt = con.createStatement();

            dm.setRowCount(0);
            String sql2 = "SELECT `course_id`, `course name`, `semester` FROM `course`;";
            ResultSet ck = smt.executeQuery(sql2);
            while (ck.next()) {
                    CreatRows(ck.getString("course name"), ck.getString("semester"));
            }
        }
        catch(Exception e){
            
        }
    }
    
    void openpdf(String file){
        try {
            SwingController control = new SwingController();
            SwingViewBuilder factry = new SwingViewBuilder(control);
            JPanel viewerCompntpnl = factry.buildViewerPanel();
            ComponentKeyBinding.install(control, viewerCompntpnl);
            control.getDocumentViewController().setAnnotationCallback(
                new org.icepdf.ri.common.MyAnnotationCallback(
                control.getDocumentViewController()));
            control.openDocument(file);
            jScrollPane3.setViewportView(viewerCompntpnl);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
}
